
package br.com.projetoinfantil.view;

import br.com.projetoinfantil.dao.FilhoDao;
import br.com.projetoinfantil.model.Filho;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 181810035
 */
public class FrmCadastrarFilhos extends javax.swing.JFrame {

    public FrmCadastrarFilhos() {
        initComponents();
        setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) tbfilhos.getModel();
        tbfilhos.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) tbfilhos.getModel();
        modelo.setNumRows(0);
        FilhoDao udao = new FilhoDao();

        for (Filho u : udao.read()) {

            modelo.addRow(new Object[]{
                u.getIdFilho(),
                u.getNomeFilho(),
                u.getSexoFilho(),});

        }
    }

    public void readForDesc(String nome) {
        DefaultTableModel modelo = (DefaultTableModel) tbfilhos.getModel();
        modelo.setNumRows(0);
        FilhoDao pdao = new FilhoDao();

        for (Filho u : pdao.readForDesc(nome)) {
            modelo.addRow(new Object[]{
                u.getIdFilho(),
                u.getNomeFilho(),
                u.getSexoFilho(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbCadastroFilhos = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        txtNomeFilho = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        lbDataDeNascimento = new javax.swing.JLabel();
        txtDataDeNascimentoFilho = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbfilhos = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtPesquisarFilho = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtpai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCadastroFilhos.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbCadastroFilhos.setForeground(new java.awt.Color(255, 255, 255));
        lbCadastroFilhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_kids_together_mom-01_3181663.png"))); // NOI18N
        lbCadastroFilhos.setText("CADASTRE SEU FILHO");
        getContentPane().add(lbCadastroFilhos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbNome.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome");
        getContentPane().add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lbSexo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(255, 255, 255));
        lbSexo.setText("Sexo:");
        getContentPane().add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtNomeFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFilhoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeFilho, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 300, 30));

        rbMasculino.setText("Masculino");
        getContentPane().add(rbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        rbFeminino.setText("Feminino");
        getContentPane().add(rbFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lbDataDeNascimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbDataDeNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lbDataDeNascimento.setText("Data de nascimento");
        getContentPane().add(lbDataDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        txtDataDeNascimentoFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDeNascimentoFilhoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataDeNascimentoFilho, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 120, 30));

        tbfilhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data de nascimento", "sexo", "Pai"
            }
        ));
        tbfilhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfilhosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbfilhos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 92));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_save_1608823.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 90, 30));

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_Streamline-22_185042.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 90, 30));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_Streamline-70_185090.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 100, 30));

        txtPesquisarFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarFilhoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisarFilho, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 150, 30));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder_system-search_118797.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 110, 30));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pais");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtpai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtpai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background FrmCadastrarFilhos.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 620, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbfilhosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfilhosMouseClicked
        if (tbfilhos.getSelectedRow() != -1) {

            txtNomeFilho.setText(tbfilhos.getValueAt(tbfilhos.getSelectedRow(), 0).toString());
            txtDataDeNascimentoFilho.setText(tbfilhos.getValueAt(tbfilhos.getSelectedRow(), 1).toString());
            if(tbfilhos.getValueAt(tbfilhos.getSelectedRow(), 2).toString().equals("Feminino")){
                rbFeminino.setSelected(true);
            }            else{
                rbMasculino.setSelected(true);
            }
            txtpai.setText(tbfilhos.getValueAt(tbfilhos.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_tbfilhosMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Filho u = new Filho();
        FilhoDao dao = new FilhoDao();
        u.setNomeFilho(txtNomeFilho.getText());
        if(rbFeminino.isSelected()){
        u.setSexoFilho("Feminino");
        }else{
            u.setSexoFilho("Masculino");
        }
        u.setFkidPai(WIDTH);
        
        dao.create(u);
        txtNomeFilho.setText("");
        txtDataDeNascimentoFilho.setText("");
        rbMasculino.setText("");
        rbFeminino.setText("");

        readJTable();

    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtNomeFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFilhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFilhoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (tbfilhos.getSelectedRow() != -1) {

            Filho u = new Filho();
            FilhoDao dao = new FilhoDao();

            u.setNomeFilho(txtNomeFilho.getText());
            u.setSexoFilho(rbMasculino.getText());
            u.setSexoFilho(rbFeminino.getText());
            dao.update(u);

            txtNomeFilho.setText("");
            txtDataDeNascimentoFilho.setText("");
            rbMasculino.setText("");
            rbFeminino.setText("");

            readJTable();

        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (tbfilhos.getSelectedRow() != -1) {

            Filho u = new Filho();
            FilhoDao dao = new FilhoDao();

            u.setIdFilho((int) tbfilhos.getValueAt(tbfilhos.getSelectedRow(), 0));

            dao.delete(u);

            txtNomeFilho.setText("");
            txtDataDeNascimentoFilho.setText("");
            rbMasculino.setText("");
            rbFeminino.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um filho para excluir do cadastro.");
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtPesquisarFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarFilhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarFilhoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        readForDesc(txtPesquisarFilho.getText());
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txtDataDeNascimentoFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDeNascimentoFilhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDeNascimentoFilhoActionPerformed

    private void txtpaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarFilhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarFilhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarFilhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarFilhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastrarFilhos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCadastroFilhos;
    private javax.swing.JLabel lbDataDeNascimento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tbfilhos;
    private javax.swing.JTextField txtDataDeNascimentoFilho;
    private javax.swing.JTextField txtNomeFilho;
    private javax.swing.JTextField txtPesquisarFilho;
    private javax.swing.JTextField txtpai;
    // End of variables declaration//GEN-END:variables
}
