/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoinfantil.view;

import br.com.projetoinfantil.dao.UsuarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Hegon
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
         setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();
        ctLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        csSenha = new javax.swing.JPasswordField();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 0));
        txtLogin.setText("Login:");
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        txtSenha.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 0));
        txtSenha.setText("Senha:");
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));
        getContentPane().add(ctLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 240, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Logar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));
        getContentPane().add(csSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 240, 30));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background FrmLogin.png"))); // NOI18N
        img.setText("jLabel1");
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1060, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  UsuarioDao dao = new UsuarioDao();
       
       if(dao.checkLogin(ctLogin.getText(), csSenha.getText())){
           new FrmMenu().setVisible(true);
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Senha incorreta!");
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField csSenha;
    private javax.swing.JTextField ctLogin;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
