/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoinfantil.view;

import br.com.projetoinfantil.dao.UsuarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Hegon
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();
        ctLogin = new javax.swing.JTextField();
        btLogar = new javax.swing.JButton();
        csSenha = new javax.swing.JPasswordField();
        btCadastrar = new javax.swing.JButton();
        lbLoginIncorreto = new javax.swing.JLabel();
        lbSenhaIncorreta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        txtLogin.setText("Login:");
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 20));

        txtSenha.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        txtSenha.setText("Senha:");
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));
        getContentPane().add(ctLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, 30));

        btLogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLogar.setText("Logar");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 30));
        getContentPane().add(csSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, 30));

        btCadastrar.setText("Cadastre-se");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 20));
        getContentPane().add(lbLoginIncorreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, 20));
        getContentPane().add(lbSenhaIncorreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        String login = ctLogin.getText();
        String senha = String.copyValueOf(csSenha.getPassword());

        UsuarioDao dao = new UsuarioDao();

        if (dao.checkLogin(ctLogin.getText(), csSenha.getText())) {
            new FrmCadastrarFilhos().setVisible(true);
            this.dispose();
        } else if (login.length() == 0 && senha.length() == 0){
            lbLoginIncorreto.setText("Insira seu login.");
            lbSenhaIncorreta.setText("Insira sua senha.");
        } else if (login.length() == 0){
            lbSenhaIncorreta.setText("");
            lbLoginIncorreto.setText("Insira seu login.");
        } else if (senha.length() == 0) {
            lbSenhaIncorreta.setText("Insira sua senha.");
            lbLoginIncorreto.setText("");
        } else {            
            lbSenhaIncorreta.setText("Login ou senha incorreto(s)");
        }

    }//GEN-LAST:event_btLogarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        new FrmCadastrarPais().setVisible(true);

    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLogar;
    private javax.swing.JPasswordField csSenha;
    private javax.swing.JTextField ctLogin;
    private javax.swing.JLabel lbLoginIncorreto;
    private javax.swing.JLabel lbSenhaIncorreta;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtSenha;
    // End of variables declaration//GEN-END:variables
}
